substitutions:
  name: reterminal-e1002
  friendly_name: "reTerminal E1002"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: 600
      then:
        - output.turn_on: bsp_sd_enable
        - output.turn_on: bsp_battery_enable
        - delay: 200ms
        - component.update: battery_voltage
        - component.update: battery_level
        - light.turn_on: onboard_led
    - priority: -100
      then:
        - delay: 5s
        - script.execute: handle_wakeup
        - script.execute: reset_sleep_timer

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  hardware_uart: UART0 # Required to report logs over USB on this device

# Enable Home Assistant API
api:
  encryption:
    key: "TxkXq5Pz+YRQ0ONdHkmPcXTS9QPDH7wJwuAc2/fYXIs="

ota:
  - platform: esphome
    password: "06f502b3365e22af2ef1d0b659932ecb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Reterminal-E1002"
    password: "QCmvGq69TNgH"

deep_sleep:
  id: deep_sleep_1
  wakeup_pin: GPIO3
  wakeup_pin_mode: INVERT_WAKEUP

psram:
  mode: octal
  speed: 80MHz

font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 20
    glyphsets:
      - GF_Latin_Core
      - GF_Cyrillic_Core

  - file:
      type: gfonts
      family: Roboto
      weight: 700    # bold
    id: font_small_bold
    size: 20
    glyphsets:
      - GF_Latin_Core
      - GF_Cyrillic_Core

captive_portal:

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO9

i2c:
  scl: GPIO20
  sda: GPIO19

globals:
  - id: page_index
    type: int
    restore_value: true
    initial_value: '0'
  - id: sleep_timer_seconds
    type: int
    restore_value: false
    initial_value: '0'

  - id: image_home_loading
    type: bool
    restore_value: false
    initial_value: 'false'
  - id: image_picture_loading
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: timeout_reached
    type: bool
    restore_value: False
    initial_value: 'false'

  - id: script_running
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: last_update_str
    type: std::string
    restore_value: false
    initial_value: "\"--:--\""

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature"
      id: temp_sensor
    humidity:
      name: "Relative Humidity"
      id: hum_sensor
    update_interval: 90s
  - platform: adc
    pin: GPIO1
    name: "Battery Voltage"
    id: battery_voltage
    update_interval: 90s
    attenuation: 12db
    filters:
      - multiply: 2.0
    on_value:
      then:
        - component.update: battery_level
  - platform: template
    name: "Battery Level"
    id: battery_level
    unit_of_measurement: "%"
    icon: "mdi:battery"
    device_class: battery
    state_class: measurement
    lambda: 'return id(battery_voltage).state;'
    update_interval: never
    filters:
      - calibrate_linear:
          - 4.15 -> 100.0
          - 3.96 -> 90.0
          - 3.91 -> 80.0
          - 3.85 -> 70.0
          - 3.80 -> 60.0
          - 3.75 -> 50.0
          - 3.68 -> 40.0
          - 3.58 -> 30.0
          - 3.49 -> 20.0
          - 3.41 -> 10.0
          - 3.30 -> 5.0
          - 3.27 -> 0.0
      - clamp:
          min_value: 0
          max_value: 100

output:
  - platform: gpio
    pin: GPIO6
    id: bsp_led
    inverted: true
  - platform: gpio
    pin: GPIO16
    id: bsp_sd_enable
  - platform: gpio
    pin: GPIO21
    id: bsp_battery_enable

light:
  - platform: binary
    name: "Onboard LED"
    output: bsp_led
    id: onboard_led
    internal: true

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Moscow"

text_sensor:
  - platform: homeassistant
    id: ha_page_selector
    entity_id: input_select.reterminal_e1002_page_selector
    internal: true
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
      id: sensorip
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
      id: sensorssid

interval:
  - interval: 1s
    then:
      - lambda: |-
          id(sleep_timer_seconds)++;
          if (id(sleep_timer_seconds) % 30 == 0) {
            ESP_LOGI("sleep_timer", "Timer at %d seconds", id(sleep_timer_seconds));
          }
          if (id(sleep_timer_seconds) >= 120) {
            ESP_LOGI("sleep_timer", "120 seconds elapsed, checking time and entering sleep");
            id(sleep_timer_seconds) = 0;
            id(check_time_and_sleep).execute();
          }

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    id: right
    name: "Right"
    internal: true
    on_press:
      then:
        - script.execute: reset_sleep_timer
        - lambda: |-
            id(page_index) = (id(page_index) + 1) % 2;
        - if:
            condition:
              lambda: 'return id(page_index) == 0;'
            then:
              - component.update: dashboard_image_home
        - if:
            condition:
              lambda: 'return id(page_index) == 1;'
            then:
              - component.update: dashboard_image_picture

  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    id: left
    name: "Left"
    internal: true
    on_press:
      then:
        - script.execute: reset_sleep_timer
        - lambda: |-
            id(page_index) = (id(page_index) - 1 + 2) % 2;
        - if:
            condition:
              lambda: 'return id(page_index) == 0;'
            then:
              - component.update: dashboard_image_home
        - if:
            condition:
              lambda: 'return id(page_index) == 1;'
            then:
              - component.update: dashboard_image_picture

http_request:
  verify_ssl: false
  timeout: 30s
  watchdog_timeout: 40s

script:

  - id: set_last_update_time
    mode: queued
    then:
      - lambda: |-
          auto t = id(homeassistant_time).now();
          if (t.is_valid()) {
            char buf[6];
            snprintf(buf, sizeof(buf), "%02d:%02d", t.hour, t.minute);
            id(last_update_str) = buf;
          } else {
            id(last_update_str) = "--:--";
          }

  - id: start_image_update
    mode: queued
    then:
      - lambda: |-
          ESP_LOGI("image_loader", "=== Starting image update process ===");
          id(image_picture_loading) = true;
          id(timeout_reached) = false;
      - if:
          condition:
            lambda: 'return id(page_index) == 0;'
          then:
            - component.update: dashboard_image_home
      - if:
          condition:
            lambda: 'return id(page_index) == 1;'
          then:
            - component.update: dashboard_image_picture
      - delay: 500ms
      - lambda: |-
          if (!id(image_picture_loading)) {
            ESP_LOGE("image_loader", "ERROR: Image update failed to start!");
          } else {
            ESP_LOGI("image_loader", "Image update started successfully");
          }

  - id: reset_sleep_timer
    mode: queued
    then:
      - lambda: |-
          ESP_LOGI("sleep_timer", "Timer reset to 0");
          id(sleep_timer_seconds) = 0;

  - id: handle_wakeup
    mode: single
    then:
      - lambda: |-
          auto wakeup_cause = esp_sleep_get_wakeup_cause();
          ESP_LOGI("wakeup", "Wakeup cause: %d (0=undefined, 2=ext0/GPIO, 4=timer)", wakeup_cause);

          if (wakeup_cause == ESP_SLEEP_WAKEUP_EXT0) {
            ESP_LOGI("wakeup", "GPIO3 wakeup - will refresh current page (index: %d)", id(page_index));
          } else {
            ESP_LOGI("wakeup", "Timer/normal boot - checking HA page selector");

            if (id(ha_page_selector).has_state()) {
              std::string page_selection = id(ha_page_selector).state;
              ESP_LOGI("wakeup", "HA selector value: %s", page_selection.c_str());

              if (page_selection == "home") {
                id(page_index) = 0;
              } else if (page_selection == "picture") {
                id(page_index) = 1;
              } else {
                ESP_LOGW("wakeup", "Unknown selector value, defaulting to home");
                id(page_index) = 0;
              }
            } else {
              ESP_LOGW("wakeup", "HA selector not available, defaulting to home");
              id(page_index) = 0;
            }
          }

          ESP_LOGI("wakeup", "Page index set to: %d, will trigger update", id(page_index));
      - delay: 200ms
      - lambda: |-
          ESP_LOGI("wakeup", "Executing component update for page: %d", id(page_index));
          switch(id(page_index)) {
            case 0:
              ESP_LOGI("wakeup", "Updating dashboard_image_home");
              id(dashboard_image_home).update();
              break;
            case 1:
              ESP_LOGI("wakeup", "Updating dashboard_image_picture");
              id(dashboard_image_picture).update();
              break;
            default:
              ESP_LOGW("wakeup", "Invalid page index %d, updating home", id(page_index));
              id(dashboard_image_home).update();
          }

  - id: check_time_and_sleep
    mode: single
    then:
      if:
        condition:
          lambda: 'return !id(script_running);'
        then:
          - lambda: |-
              id(script_running) = true;
              ESP_LOGI("sleep_script", "Starting check_time_and_sleep execution");
              auto time = id(homeassistant_time).now();
              if (!time.is_valid()) {
                ESP_LOGW("sleep_script", "Time not available, sleeping for 30 minutes");
                id(onboard_led).turn_off();
                id(deep_sleep_1).set_sleep_duration(30 * 60 * 1000);
                id(script_running) = false;
                id(deep_sleep_1).begin_sleep();
                id(script_running) = false;
                return;
              }

              int hour = time.hour;
              int minute = time.minute;
              ESP_LOGI("sleep_script", "Current time: %02d:%02d", hour, minute);

              if (hour >= 22 || hour < 6) {
                ESP_LOGI("sleep_script", "Night time (22:00-06:00), switching to wallpaper page");
                id(page_index) = 1;
              }
          - if:
              condition:
                lambda: |-
                  auto time = id(homeassistant_time).now();
                  int hour = time.hour;
                  return (hour >= 22 || hour < 6);
              then:
                - script.execute: start_image_update  
                - delay: 30s
                - lambda: |-
                    auto time = id(homeassistant_time).now();
                    int hour = time.hour;
                    int minute = time.minute;

                    int minutes_until_6am;
                    if (hour >= 22) {
                      minutes_until_6am = ((24 - hour) * 60 - minute) + (6 * 60);
                    } else {
                      minutes_until_6am = (6 - hour) * 60 - minute;
                    }
                    ESP_LOGI("sleep_script", "Sleeping for %d minutes until 6am", minutes_until_6am);
                    id(deep_sleep_1).set_sleep_duration(minutes_until_6am * 60 * 1000);
                    id(script_running) = false;
                    id(deep_sleep_1).begin_sleep(); 
              else:
                - lambda: |-
                    ESP_LOGI("sleep_script", "Day time (06:00-22:00), sleeping for 60 minutes");
                    id(onboard_led).turn_off();
                    id(deep_sleep_1).set_sleep_duration(60 * 60 * 1000);
                    id(script_running) = false;
                    id(deep_sleep_1).begin_sleep();
          - lambda: |-
              id(script_running) = false;
              ESP_LOGI("sleep_script", "Script execution completed, script_running reset to false");
        else:
          - lambda: |-
              ESP_LOGI("sleep_timer", "Script already running, skipped execution");


online_image:
  - id: dashboard_image_home
    format: PNG
    type: RGB565
    buffer_size: 65536
    url: http://192.168.50.35:10000/test-reterminal/home?device=seeed-reterminal-e1002&theme=Graphite+Auto&zoom=1.219&lang=ru&next=600
    update_interval: never
    on_download_finished:
      - lambda: |-
          id(image_home_loading) = false;
          ESP_LOGI("image_loader", "Finished download of dashboard_image_home");
      - script.execute: set_last_update_time
      - delay: 100ms
      - component.update: epaper_display
    
  - id: dashboard_image_picture
    format: JPEG
    type: RGB565
    buffer_size: 65536
    url: http://192.168.50.35:10000/test-reterminal/picture?device=seeed-reterminal-e1002&dithering=jarvis-judice-ninke&format=jpeg&lang=ru
    update_interval: never
    on_download_finished:
      - lambda: |-
          id(image_picture_loading) = false;
          ESP_LOGI("image_loader", "Finished download of dashboard_image_picture");
      - script.execute: set_last_update_time
      - delay: 100ms
      - component.update: epaper_display

display:
  - platform: epaper_spi
    id: epaper_display
    model: Seeed-reTerminal-E1002
    #full_update_every: 10
    update_interval: never
    lambda: |-
      Color CLR;
      if (id(page_index) == 0) {
        it.image(0, 0, id(dashboard_image_home));
        CLR = Color(0, 0, 0, 0);
      } else if (id(page_index) == 1) {
        it.image(0, 0, id(dashboard_image_picture));
        CLR = Color(255, 0, 0, 0);
      }
      it.printf(10, 460, id(font_small_bold), CLR, "Обновлено: %s", id(last_update_str).c_str());
